.PHONY: upstream
upstream: qtsolutions

.PHONY: qtsolutions 
qtsolutions: qtcolortriangle

qtcolortriangle:
	@cd QtSolutions/qtcolortriangle-2.6_1-opensource ; \
	echo "license accepted" > .licenseAccepted ; \
	./configure


