.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH picogen 1 "June 11, 2010" "" "picogen"

.SH NAME
picogen-simplex, picohelp, picogen-quatsch-editor \- program for...

.SH SYNOPSIS
.B picogen
.RI [ options ]
.br

.SH DESCRIPTION
The programs
.B picogen-simplex, picohelp, picogen-quatsch-editor
are part of the 
.B picogen package
 and provide a free terrain synthesizer and renderer. The
above mentioned programs are exclusively dedicated to graphical
usage. Please run 
.B picohelp
for documentation, or invoke 
.B picogen-simplex
or
.B picogen-quatsch-editor
to find inline- and context-sensitive information.
.PP

.SH OPTIONS
.B
.IP -OPTION
This option...

.SH "SEE ALSO"

