.\"Created with GNOME Manpages Editor Wizard
.\"http://sourceforge.net/projects/gmanedit2
.TH picogen-quatsch-editor 1 "June 1, 2010" "" "picogen-quatsch-editor"

.SH NAME
picogen-quatsch-editor \- program for...

.SH SYNOPSIS
.B picogen-quatsch-editor
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B picogen-quatsch-editor
program. This program...
.PP
\fBpicogen-quatsch-editor\fP is for...

.SH OPTIONS
.B
.IP -OPTION
This option...

.SH "SEE ALSO"

