/***************************************************************************
 *            MkheightmapWxDialog.h
 *
 *  Copyright  2008  Sebastian Mach
 *  phresnel@gmail.com
 ****************************************************************************/

/*
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; version 3 of the License, or (at your
 *  option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */
 
 
 
#ifndef __MkheightmapWxDialog__
#define __MkheightmapWxDialog__

/**
@file
Subclass of MkheightmapWxDialogGui, which is generated by wxFormBuilder.
*/

#include "auto/mkheightmap_wx_gui.h"

/** Implementing MkheightmapWxDialogGui */
class MkheightmapWxDialog : public MkheightmapWxDialogGui
{
private:
    void UpdateTextWithTemplate (const wxString &tpl);

    void GetYprOrientation (float &yaw, float &pitch, float &roll) const;
    void GetYprPosition (float &x, float &y, float &z) const;
    void ObtainSunSkyParams (
        float atmoRGB [3], 
        float &fogDensity, float &fogRange,
        float &turbidity,
        float &sunDiskSize,
        bool &falloffEnable, float falloffParameters [3],
        float sunRGB [3], float sunDir [3]
    ) const ;

    std::string generateSceneTempFile (bool withPreviewSettings) const;

protected:
	// Handlers for MkheightmapWxDialogGui events.
	void OnExecute( wxCommandEvent& event );
	void OnClose( wxCommandEvent& event );
	void OnRender ( wxCommandEvent& event );
	void OnAutoformat( wxCommandEvent& event );
	void OnOpenSaveFile( wxCommandEvent& event );
	void OnQuickPreview( wxCommandEvent& event );
	void OnShowHemisphere( wxCommandEvent& event );
	void OnFast1MakeChoice ( wxCommandEvent& event );
	void OnFast2MakeChoice ( wxCommandEvent& event );
	void OnFast3MakeChoice ( wxCommandEvent& event );
	void OnFast4MakeChoice ( wxCommandEvent& event );
	void OnFast5MakeChoice ( wxCommandEvent& event );
	void OnFast6MakeChoice ( wxCommandEvent& event );
	void OnPresets1 ( wxCommandEvent& event );
    void OnMenu_Execute (wxCommandEvent& event);
    void OnMenu_Copyright (wxCommandEvent& event);
	
public:
	/** Constructor */
	MkheightmapWxDialog( wxWindow* parent );
};

#endif // __MkheightmapWxDialog__
